vcs = vcs 
FLAGS = -R -full64 -debug_acc+all -sverilog -f

default:
	$(vcs) $(FLAGS) run.f


maintainer-copy::
clean mostlclean distclean maintainer-clean::
	-rm -rf csrc simv simv.daidir ucli.key verdiLog VerdiLog novas.conf novas.rc novas_dump.log *.fsdb 
